-- Table pour les pré-inscriptions publiques au club
CREATE TABLE IF NOT EXISTS preinscriptions (
    id INT PRIMARY KEY AUTO_INCREMENT,
    nom VARCHAR(100) NOT NULL,
    prenom VARCHAR(100) NOT NULL,
    adresse_ligne1 VARCHAR(255) NOT NULL,
    adresse_ligne2 VARCHAR(255) DEFAULT NULL,
    code_postal VARCHAR(10) NOT NULL,
    ville VARCHAR(100) NOT NULL,
    pays VARCHAR(100) DEFAULT 'France',
    telephone VARCHAR(20) NOT NULL,
    gsm VARCHAR(20) NOT NULL,
    email VARCHAR(255) NOT NULL,
    date_naissance DATE NOT NULL,
    profession VARCHAR(150) NOT NULL,
    contact_urgence_nom VARCHAR(150) NOT NULL,
    contact_urgence_tel VARCHAR(20) NOT NULL,
    contact_urgence_email VARCHAR(255) NOT NULL,
    photo_filename VARCHAR(255) DEFAULT NULL,
    presentation TEXT NOT NULL,
    est_pilote TINYINT(1) DEFAULT 0,
    numero_licence VARCHAR(50) DEFAULT NULL,
    statut ENUM('en_attente', 'validee', 'refusee') DEFAULT 'en_attente',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    validated_at TIMESTAMP NULL DEFAULT NULL,
    validated_by INT NULL,
    user_id INT NULL COMMENT 'ID utilisateur créé si validé',
    notes_admin TEXT DEFAULT NULL,
    INDEX idx_statut (statut),
    INDEX idx_email (email),
    INDEX idx_created (created_at),
    FOREIGN KEY (validated_by) REFERENCES users(id) ON DELETE SET NULL,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
